- hosts: kauai
  tags: git
  tasks:
    - name: install git
      package:
        name: git
        state: present
      become: yes
    - name: configure git globally
      copy:
        src="git/dot.git{{ item }}"
        dest="{{ ansible_user_dir }}/.git{{ item }}"
      with_items:
        - config
        - ignore
