# Requirements, install using
# ansible-galaxy install -r requirements.yml

# from git
- src: https://github.com/kahalemakai/ansible-ripgrep
  name: ripgrep
- src: https://github.com/kahalemakai/ansible-build-awesome-wm
  name: build-awesome-wm
#  version: master # this has to be a tag.
