" this file has been auto-generated by ansible
"
" any changes to it will be overridden automatically

set tabstop=4
set shiftwidth=4
set smarttab
set softtabstop=4
set tabstop=8
set autoindent
set expandtab
