" this file has been auto-generated by ansible
"
" any changes to it will be overridden automatically

set tabstop=2
set shiftwidth=2
set smarttab
set softtabstop=2
set tabstop=8
set autoindent
set expandtab
